server:
  port: 8003


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abc123
    url: jdbc:mysql://10.3.1.120:3306/sports?useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true